### ISSUE TITLE
Make build process consistent with eurekaclinical-analytics-webclient

### ISSUE THREAD

**Issue by arpost** [eurekaclinical/eurekaclinical-admin-webclient#15]
I'd like to make the build process consistent across our web clients, just like we do with our backend Java applications. The behavior is:

1) mvn clean install or mvn install; just builds.
2) mvn clean install -Pwebserver; builds, starts the embedded web server, and opens up the user's web browser to the main page.
3) mvn dist: builds the zip file.

**Comment by ndeshpa** [comment]
Done.
