### ISSUE TITLE
pom.xml overrides plugin versions from eurekaclinical-parent

### ISSUE THREAD

**Issue by arpost** [eurekaclinical/eurekaclinical-admin-webclient#16]
The following plugins have their version number overridden. In general, we try to avoid this so that the behavior of the plugins is clearly understood. The plugins in question are:

1) maven-resources-plugin
2) frontend-maven-plugin
3) maven-notice-plugin

**Comment by ndeshpa** [comment]
Updated versions to match parent pom.
