### ISSUE TITLE
Clicking Admin goes back to the main page

### ISSUE THREAD

**Issue by arpost** [eurekaclinical/eurekaclinical-admin-webclient#23]
It has to be a hyperlink to make the styling work, but clicking on it should not change the page that you are on. In angularjs 1, this is a hyperlink "a" tag with href="#", but that does not seem to work here.

**Comment by ndeshpa** [comment]
href="#" behavior in Angular2 and up has changed to reload the page, thereby navigating to the home page. I've worked around it and fixed the behavior so clicking on the link will not result in navigating away from the current page.
