### ISSUE TITLE
Issue with login workflow

### ISSUE THREAD

**Issue by arpost** [eurekaclinical/eurekaclinical-admin-webclient#25]
When running the webclient locally with maven in combination with the webapp running in cargo, there is a problem with the login process. The user always has an active CAS session. So, when the webclient first loads, it should call /protected/get-session, and the user should be logged in automatically. Currently, when the webclient first loads, the user is not logged in. When the user clicks Login, he/she is redirected back to the main page of the webclient and a 400 error message appears at the top of the screen. Reloading the page in the browser makes the error go away, and the user is finally logged in.

**Comment by ndeshpa** [comment]
Fixed Issue.
